name: PARSE

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: yarn install

      - run: yarn parse
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      - name: commit changes
        uses: github-actions-x/commit@v2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'feat(*): update library components'
          force-add: 'false'
          files: data/*
          name: reme3d2y
          email: reme3d2y@gmail.com
